name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Subfolder to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend
          branch: gh-pages
